<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <!--<NoWin32Manifest>true</NoWin32Manifest>-->
    <!--<ApplicationIcon>Icon\ProgramIcon.ico</ApplicationIcon>-->
    
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <Optimize>False</Optimize>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <Optimize>False</Optimize>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Views\Pages\OLD\**" />
    <EmbeddedResource Remove="Views\Pages\OLD\**" />
    <None Remove="Views\Pages\OLD\**" />
    <Page Remove="Views\Pages\OLD\**" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="License\AdditionalLicense.txt" />
    <None Remove="License\License.txt" />
    <None Remove="Ressources\CsvFiles\heavyappentries.csv" />
    <None Remove="Ressources\CsvFiles\workout_data.csv" />
    <None Remove="Ressources\Images\Body-Fat-Percentage-Calculator-Caliper-Male-Female.jpg" />
    <None Remove="Ressources\JsonFiles\Database_Exercises.json" />
    <None Remove="Ressources\JsonFiles\exercises.json" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Icon\ProgramIcon.ico">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="License\AdditionalLicense.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="License\License.txt">
      <Generator>MSBuild:Compile</Generator>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Ressources\CsvFiles\heavyappentries.csv">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Ressources\CsvFiles\workout_data.csv">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Ressources\JsonFiles\Database_Exercises.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <Content Include="Ressources\Images\Body-Fat-Percentage-Calculator-Caliper-Male-Female.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Ressources\JsonFiles\exercises.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="CsvHelper" Version="33.1.0" />
    <PackageReference Include="LiveChartsCore" Version="2.0.5" />
    <PackageReference Include="LiveChartsCore.SkiaSharpView" Version="2.0.5" />
    <PackageReference Include="LiveChartsCore.SkiaSharpView.WPF" Version="2.0.5" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.142" />
    <PackageReference Include="MySqlConnector" Version="2.6.1" />
    <PackageReference Include="Portkit.ComponentModel" Version="1.1.2" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Views\Pages\Main\MultiImportPage.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\Pages\Main\StepDailyTrendIMportPage.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
</Project>
